### ISSUE TITLE
empty popup if <i> is in abbr

### ISSUE THREAD

**Issue by My1** [Tyriar/abbr-touch#10]
well I have some icons (Fontawesome) that I explain using an abbr, but I just noticed that when having an <i> (often used for icons) inside an abbr then it seems to fail and give an empty popup.

**Comment by Tyriar** [comment]
Thanks for the report

**Comment by My1** [comment]
is there something I can do about that?

**Comment by Tyriar** [comment]
Not off the top of my head. To clarify, are you doing this?

```html
<abbr title="A car"><i class="fa fa-car"></i></abbr>
```

Answering these questions would be helpful:
- Are you passing a `customTapHandler` into `abbrTouch`?
- Could you also check if there are any errors in the console?
- Also are using a touch device or touch emulation, not a mouse?

**Comment by My1** [comment]
pretty much that example fits it. I use a touch device (galaxy Note 4 with forefox)
I use the normal way with alerts
and the altert itself comes up but with no content, as in alert(""); (or however that would be expressed with js, I am not well versed in that...

**Comment by Tyriar** [comment]
Reproduced it here: https://output.jsbin.com/himacagifu

The problem is happening because the touched element on which the tap handler is being called upon is the `<i>`, not the `<abbr>`. This might be a bug in https://github.com/Tyriar/touchtap-event

I'll have to do a bit of a deeper dive later on but in the meantime a work around is to use this touch handler:

```js
abbrTouch(document.body, function (target, title, touchX, touchY) {
  var abbr = target;
  while (abbr.tagName !== 'ABBR') {
    abbr = abbr.parentNode;
  }
  
  // Actual handler
  alert(abbr.title);
});
```

Demo here:
- https://jsbin.com/hifuwutona/1/edit?html,css,output
- https://output.jsbin.com/hifuwutona/1

Thanks again for reporting!

**Comment by My1** [comment]
okay seems to work, mostly,  (I put it in my implementation as jsbin has the problem of not working after 90 mins if posted by anonymous, at least that's what they say) and CHromes does as it should, but FIrefox somehow gets 2 alterts.

**Comment by Tyriar** [comment]
Fixed and published the fix to npm. The issue was that `Event.target` was being passed into the tap handler instead of `Event.currentTarget`.
